//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuronDocumentSync.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuronDocumentSync.Resources.MainMessages", typeof(MainMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not install the service.
        /// </summary>
        public static string rs_CanNotInstallService {
            get {
                return ResourceManager.GetString("rs_CanNotInstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read the service status.
        /// </summary>
        public static string rs_CanNotReadServiceStatus {
            get {
                return ResourceManager.GetString("rs_CanNotReadServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not start not installed service.
        /// </summary>
        public static string rs_CanNotStartNotInstalledService {
            get {
                return ResourceManager.GetString("rs_CanNotStartNotInstalledService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not start the service.
        /// </summary>
        public static string rs_CanNotStartService {
            get {
                return ResourceManager.GetString("rs_CanNotStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not stop the service.
        /// </summary>
        public static string rs_CanNotStopService {
            get {
                return ResourceManager.GetString("rs_CanNotStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not uninstall the service.
        /// </summary>
        public static string rs_CanNotUninstallService {
            get {
                return ResourceManager.GetString("rs_CanNotUninstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read FbDb Section from the main configuration file..
        /// </summary>
        public static string rs_CantReadFbDbConfigSection {
            get {
                return ResourceManager.GetString("rs_CantReadFbDbConfigSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read General Section from the main configuration file..
        /// </summary>
        public static string rs_CantReadGeneralConfigSection {
            get {
                return ResourceManager.GetString("rs_CantReadGeneralConfigSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current service may executed with such parameters:.
        /// </summary>
        public static string rs_CommansInfo {
            get {
                return ResourceManager.GetString("rs_CommansInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        public static string rs_ErrorOccurred {
            get {
                return ResourceManager.GetString("rs_ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found errors in the work with DB.
        /// </summary>
        public static string rs_ErrorsInRepository {
            get {
                return ResourceManager.GetString("rs_ErrorsInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NeuronRepository Exception in GetUnhandledDocumentsInfo.
        /// </summary>
        public static string rs_ErrorsInRepositoryGetUnhandledDocumentsInfo {
            get {
                return ResourceManager.GetString("rs_ErrorsInRepositoryGetUnhandledDocumentsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while changing the service failure actions.
        /// </summary>
        public static string rs_ErrorWhileChangingServiceFailureActions {
            get {
                return ResourceManager.GetString("rs_ErrorWhileChangingServiceFailureActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while installing the service.
        /// </summary>
        public static string rs_ErrorWhileInstallingService {
            get {
                return ResourceManager.GetString("rs_ErrorWhileInstallingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uninstalling the service.
        /// </summary>
        public static string rs_ErrorWhileUninstallingService {
            get {
                return ResourceManager.GetString("rs_ErrorWhileUninstallingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to stop.
        /// </summary>
        public static string rs_PressEnterToStop {
            get {
                return ResourceManager.GetString("rs_PressEnterToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server has an enternal error. The service will be stopped.
        /// </summary>
        public static string rs_ServerErrorServiceWillBeStopped {
            get {
                return ResourceManager.GetString("rs_ServerErrorServiceWillBeStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service installation was rolled back.
        /// </summary>
        public static string rs_ServiceInstallationWasRolledBack {
            get {
                return ResourceManager.GetString("rs_ServiceInstallationWasRolledBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is started as console application.
        /// </summary>
        public static string rs_ServiceStartedAsConsoleApplication {
            get {
                return ResourceManager.GetString("rs_ServiceStartedAsConsoleApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceTimeEnd Error value.
        /// </summary>
        public static string rs_ServiceTimeEndErrorValue {
            get {
                return ResourceManager.GetString("rs_ServiceTimeEndErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceTimeStart Error value.
        /// </summary>
        public static string rs_ServiceTimeStartErrorValue {
            get {
                return ResourceManager.GetString("rs_ServiceTimeStartErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found some problems with converting Doc file to PDF..
        /// </summary>
        public static string rs_SomeProblemsWithConvertToPdf {
            get {
                return ResourceManager.GetString("rs_SomeProblemsWithConvertToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found some problems with the Image File..
        /// </summary>
        public static string rs_SomeProblemsWithImageFile {
            get {
                return ResourceManager.GetString("rs_SomeProblemsWithImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s impossible to start main worker. 
        ///The worker is still busy..
        /// </summary>
        public static string rs_SyncCoreStartWhileBusy {
            get {
                return ResourceManager.GetString("rs_SyncCoreStartWhileBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s impossible to start main worker. 
        ///The InternalError is found..
        /// </summary>
        public static string rs_SyncCoreStartWithInternalError {
            get {
                return ResourceManager.GetString("rs_SyncCoreStartWithInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncCore didn&apos;t stop main worker thread..
        /// </summary>
        public static string rs_SyncCoreWorkerDidntStop {
            get {
                return ResourceManager.GetString("rs_SyncCoreWorkerDidntStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncronization Process is canceled by user.
        /// </summary>
        public static string rs_SyncNeuronDocumentsCanceled {
            get {
                return ResourceManager.GetString("rs_SyncNeuronDocumentsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &quot;{0}({1}) Id = {2}&quot; was not filled with all data.
        /// </summary>
        public static string rs_SyncNeuronDocumentWasNotFilled {
            get {
                return ResourceManager.GetString("rs_SyncNeuronDocumentWasNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &quot;{0}({1}) Id = {2}&quot; was not processed by the service.
        /// </summary>
        public static string rs_SyncNeuronDocumentWasNotProcessed {
            get {
                return ResourceManager.GetString("rs_SyncNeuronDocumentWasNotProcessed", resourceCulture);
            }
        }
    }
}
